### ISSUE TITLE
Matplotlib issues

### ISSUE THREAD

**Issue by htnminh** [tuanlda78202/MLE#1]
[Matplotlib](https://github.com/tuanlda78202/Machine-Learning-Tools/blob/main/Matplotlib.ipynb)

This is plain text and should not be decorated in code format.
```
`Hey guys, welcome to my notebook! I'm Charles - Major in Data Science & Artificial Intelligence at HUST.`

`This is a part of the series "Machine Learning Tools" by me. I hope you are interested in it. I would really appreciate it if you took two seconds to follow me on Github. Thank you so much!`

```

Markdown images do not exist.
![image](https://user-images.githubusercontent.com/82358580/130021722-c332e7a8-8df4-4ae8-ba78-a9e19ac1e2d1.png)

Decorations should be used here.
```
Moreover, using **";" after plot()** will hide line "<matplotlib..>"
```

Typo
```
## ❗️ `Pylot API` & `OO API`

More informations: https://bit.ly/2W28qxI
```

Typo
```
 ### `Pylot API` : quickly
 >allows us to interactively create simple plots.
```

Some comments do not have a space after `#`, this is one of them.
```
#change styple plt
```

Things contain information from one above line should keep format thereof.
```
## 2.2. Bar chart
>suitable for comparing values between different groups, include:
* Vertical 
* Horizontal
```

Inconsistency in code. This is one of them.
```
order_cpu = {"10105" : 100,
             "10300" :200,
             "11600": 70,
             "5900": 80,
             "5600" :50}
```

Decorations missing.
```
By setting autopct to %.0f%%, we've chosen to format the percentages with 0 decimal places (only whole numbers), and added a % sign at the end. If we had omitted the surrounding %..% symbols, the strings wouldn't be formatted as percentages, but as literal values.
```

"Strange" characters like this should never be used, decorate them instead.
```
## 2.4. Scatter  

>The scatter plot is used to represent each point (𝑥,𝑦) in two-dimensional graphs. In machine learning, when we need to represent clusters or in situations where we want to find the distribution of data points along dimensions, we will often use a scatter plot.
```

**Comment by hlongng2002241** [comment]
I got some information supporting your NumPy > Random Array

* np.random.uniform(low=0.0, high=1.0, size=None)
- This function is used for random float array in range of low and high with size is the number of entries in array
- Here is the document of uniform()

Parameters
----------
low : float or array_like of floats, optional
    Lower boundary of the output interval. All values generated will be greater 
    than or equal to low. The default value is 0.
high : float or array_like of floats
    Upper boundary of the output interval. All values generated will be less 
    than or equal to high. The default value is 1.0.
size : int or tuple of ints, optional
    Output shape. If the given shape is, e.g., (m, n, k), then m * n * k 
    are drawn. If size is None (default), a single value is returned if low 
    and high are both scalars. Otherwise, np.broadcast(low, high).size samples are drawn.

Returns
-------
out : ndarray or scalar
    Drawn samples from the parameterized uniform distribution.

Examples
--------
arr = np.random.uniform(1, 5, 5)
print(arr)

+--Run--------------------------------------------------------------+
|   [1.51121488 3.88380821 4.11311733 4.68008137 4.6700071 ]  |
+--------------------------------------------------------------------+


* Another function which is really helpful in your data preprocessing is np.random.shuffle(). You can use it to shuffle your training sets which can satisfy the randomness of input data.
- Here is the document of shuffle()

Parameters
----------
x : ndarray or MutableSequence
    The array, list or mutable sequence to be shuffled.

Returns
-------
None

Examples
--------
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

+--Run------------------------------+
|   [1 7 5 2 9 4 3 6 0 8]                      |
+------------------------------------+

**Comment by tuanlda78202** [comment]
Oh, thank you so much. I will change and add it right now. 👏🤝

**Comment by htnminh** [comment]
Remember to close it when you are done @tuanlda78202
